#加载其他配置文件
spring:
  profiles:
    active: jdbc
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: weng
  #配置redis
  redis:
    host: localhost
    port: 6379
# 日志级别
logging:
  level:
    gdut.wlz: debug
    org.springframework: info

#配置服务器
server:
  port: 80
#配置mybatis
mybatis:
  type-aliases-package: gdut.wlz.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
